spring:
  application:
    name: mytest
  mandatory-file-encoding: utf-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 9090

person:
  name: tom
  age: 18